config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'tasks/new', to: 'tasks#new', as: :new
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  get 'tasks', to: 'tasks#index', as: :tasks
  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy', as: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new()
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <% unless task.new_record? %>
    <%= f.label :completed %>
    <%= f.check_box :completed %>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
<% @tasks.each do |task| %>
<div>
<% if task.completed %>
  <input type="checkbox" id="completed" name="completed" checked onclick="return false;">
<% else %>
  <input type="checkbox" id="not-completed" name="not-completed" onclick="return false;">
<% end %>
<%= link_to "#{task.title}", task_path(task) %>. <%= link_to "x", delete_path(task),
            method: :delete,
            data: { confirm: "Are you sure?" } %><div>
<% end %>
<div><%= link_to "Create a task", new_path %><div>

app/views/tasks/new.html.erb
<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<%= link_to "Edit the task", edit_path %>
<div class="bloc">
  <%= @task.details %>
</div>
<% if @task.completed %>
  <input type="checkbox" id="completed" name="completed" checked onclick="return false;">
<% else %>
  <input type="checkbox" id="completed" name="completed" onclick="return false;">
<% end %>
<div><%= link_to "Back to list", tasks_path %></div>